name: "MySQL CMD"
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mysql:latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Check mysql Version
        run: mysql --version
        
      - name: Use files from Repo
        run: cat tests/a.txt
        
      - name: Make directory
        run: mkdir files
      - name: Change directory
        run: |
         cd files
         pwd
        
      - name: Run a multi-line script
        run: |
          pwd
          mysql --version
        # cat tests/a.txt
