name: "MySQL CMD"
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mysql:latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Use files from Repo
        run: cat tests/a.txt
        
      - name: Run a multi-line script
        run: |
          pwd
          mysql --version
          SHOW DATABASES;
        # cat tests/a.txt
