name: "MySQL CMD"
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mysql:latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Use files from Repo
        run: cat tests/*.sql
        
      - name: Run a multi-line script
        run: |
          pwd
          mysql --version
          
          mysql -u root -h 35.188.221.83 -p -P 3306
       
        # cat tests/a.txt
